-- Seed access codes + the placeholder video catalog (r2_key matches the files
-- generated by scripts/gen-test-videos.py and uploaded to the R2 bucket).

INSERT OR REPLACE INTO access_codes (code, label, condition, session_minutes, max_uses) VALUES
  ('DEMO',   'Demo 30m',  NULL, 30, NULL),
  ('FLOW30', 'Pilot 30m', NULL, 30, NULL),
  ('FLOW05', 'Pilot 5m',  NULL, 5,  NULL),
  ('QUICK2', 'Quick 2m',  NULL, 2,  NULL);

INSERT OR REPLACE INTO videos (id, slug, title, r2_key, duration_seconds, content_type, condition, sort_order) VALUES
  ('v1','count_a_01','Counting · Variation A','count_a.mp4', 8,'counting_a',NULL,1),
  ('v2','count_b_01','Counting · Variation B','count_b.mp4', 6,'counting_b',NULL,2),
  ('v3','count_c_01','Counting · Variation C','count_c.mp4',10,'counting_c',NULL,3),
  ('v4','count_a_02','Counting · Variation A','count_a.mp4', 8,'counting_a',NULL,4),
  ('v5','count_b_02','Counting · Variation B','count_b.mp4', 6,'counting_b',NULL,5),
  ('v6','count_c_02','Counting · Variation C','count_c.mp4',10,'counting_c',NULL,6);
