#!/usr/bin/env python3
"""Install downloaded selected videos into the local feed-study server.

Creates a flat video directory with one `<video_id>.mp4` per selected row and
inserts matching rows into the local SQLite catalog. Existing access-code uses
and session data are preserved.
"""

from __future__ import annotations

import argparse
import csv
import os
import shutil
import sqlite3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SELECTED = ROOT / "scripts/ig-reels-scraper/ig-data/selected-videos.csv"
DEFAULT_DOWNLOADS = ROOT / "scripts/ig-reels-scraper/ig-data/selected-downloads"
DEFAULT_OUT = ROOT / "server/data/stimulus-videos"
DEFAULT_DB = ROOT / "server/data/flowstate.sqlite"
DEFAULT_SQL = ROOT / "server/data/selected-stimuli.sql"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Import selected downloaded videos into the feed-study local server.")
    parser.add_argument("--selected-csv", type=Path, default=DEFAULT_SELECTED)
    parser.add_argument("--downloads", type=Path, default=DEFAULT_DOWNLOADS)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--db", type=Path, default=DEFAULT_DB)
    parser.add_argument("--sql", type=Path, default=DEFAULT_SQL)
    parser.add_argument("--copy", action="store_true", help="Copy MP4s instead of symlinking them.")
    parser.add_argument("--condition", default="selected_instagram")
    parser.add_argument("--clear-existing", action="store_true", help="Delete existing videos rows before inserting.")
    return parser.parse_args()


def read_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="") as f:
        return list(csv.DictReader(f))


def index_downloads(path: Path) -> dict[str, Path]:
    return {p.stem: p for p in path.rglob("*.mp4")}


def sql_quote(value: object) -> str:
    if value is None or value == "":
        return "NULL"
    if isinstance(value, (int, float)):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def install_file(src: Path, dst: Path, copy: bool) -> None:
    dst.parent.mkdir(parents=True, exist_ok=True)
    if dst.exists() or dst.is_symlink():
        dst.unlink()
    if copy:
        shutil.copy2(src, dst)
    else:
        os.symlink(src, dst)


def make_video_record(row: dict[str, str], order: int, condition: str) -> tuple[object, ...]:
    video_id = row["id"]
    username = row.get("username") or "unknown"
    selection = row.get("selection_type") or "selected"
    title = f"{username} {selection} #{row.get('selection_rank') or order}"
    slug = f"{username.replace('.', '_')}_{video_id}"
    duration = float(row.get("duration") or 0) or None
    # Keep content_type broad; richer metadata stays in selected-videos.csv and
    # offline feature exports, both keyed by this same video id.
    platform = (row.get("platform") or "instagram").strip().lower()
    content_type = "tiktok_video" if platform == "tiktok" else "instagram_reel"
    return (video_id, slug, title, f"{video_id}.mp4", duration, content_type, condition, order)


def write_sql(path: Path, records: list[tuple[object, ...]], clear_existing: bool) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "-- Generated by scripts/import-selected-videos-to-feed.py",
        "INSERT OR REPLACE INTO access_codes (code, label, condition, session_minutes, max_uses) VALUES",
        "  ('EEG30', 'EEG pilot 30m', NULL, 30, NULL),",
        "  ('EEG10', 'EEG pilot 10m', NULL, 10, NULL),",
        "  ('EEG05', 'EEG pilot 5m', NULL, 5, NULL);",
    ]
    if clear_existing:
        lines.append("DELETE FROM videos;")
    for rec in records:
        values = ", ".join(sql_quote(v) for v in rec)
        lines.append(
            "INSERT OR REPLACE INTO videos "
            "(id, slug, title, r2_key, duration_seconds, content_type, condition, sort_order) "
            f"VALUES ({values});"
        )
    path.write_text("\n".join(lines) + "\n")


def apply_db(db_path: Path, sql_path: Path) -> None:
    db_path.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(db_path)
    try:
        conn.executescript(sql_path.read_text())
        conn.commit()
    finally:
        conn.close()


def main() -> int:
    args = parse_args()
    rows = read_rows(args.selected_csv)
    downloads = index_downloads(args.downloads)
    records: list[tuple[object, ...]] = []
    missing: list[str] = []

    for order, row in enumerate(rows, start=1):
        video_id = row.get("id") or ""
        src = downloads.get(video_id)
        if not src:
            missing.append(video_id)
            continue
        install_file(src, args.out / f"{video_id}.mp4", args.copy)
        records.append(make_video_record(row, order, args.condition))

    write_sql(args.sql, records, args.clear_existing)
    apply_db(args.db, args.sql)

    print(f"Installed videos: {len(records)}")
    print(f"Missing downloads: {len(missing)}")
    print(f"Video dir: {args.out}")
    print(f"SQL: {args.sql}")
    print(f"SQLite: {args.db}")
    if missing:
        print("Missing ids:", ", ".join(missing[:20]) + (" ..." if len(missing) > 20 else ""))
    print("\nRun server with:")
    print(f"  VIDEOS_DIR={args.out} npm --prefix server run dev")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
